### ISSUE TITLE
Recipe

### ISSUE THREAD

**Issue by Tvax** [simoniz0r/Discord-AppImage#1]
Could you provide the recipe you used to generate the AppImage, so it could be added [here](https://github.com/AppImage/AppImages/tree/master/recipes) ?

**Comment by simoniz0r** [comment]
I don't at all build AppImages in the same fashion that they do.  I use a script I've created called `appimagebuild` along with AppImage build scripts to be able to create AppImages easily without having to rely on the user being on a specific distro when the AppImage is built.  All dependencies in the Discord AppImages are downloaded from Debian's repos using the latest available version at the time of build.

You can check out `appimagebuild` and my AppImage build scripts [here](https://github.com/simoniz0r/AppImages).

**Comment by Tvax** [comment]
Oh that sucks because they're definitely losing something by not adding it, nonetheless you did a great a job !
