### ISSUE TITLE
"error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by Hund** [simoniz0r/Discord-AppImage#5]
I downloaded the file `discord-stable-0.0.9-x86_64.AppImage`and when I run it I get this:

```
$ ./discord-stable-0.0.9-x86_64.AppImage
0.0.9
Discord is up to date

/tmp/.mount_discorkVPujt/usr/bin/discord: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory
$
```

I'm running Gentoo and I'm not sure what else to provide with this ticket. I thought this should be "universal"? :)

**Comment by simoniz0r** [comment]
That is something that should be installed on your system; if you don't have libcubs installed, you're doing something wrong lol.

**Comment by Hund** [comment]
I don't have a printer so I don't see why I should install cups.

**Comment by simoniz0r** [comment]
Because many applications require it to be installed.  I'm very surprised you don't have it installed already... the only logical way that happened is if you specifically compiled programs without support for libcups.

**Comment by AudioTore** [comment]
@simoniz0r lmfao
