### ISSUE TITLE
The packed version of Discord is obsolete and downloads a lot of updates.

### ISSUE THREAD

**Issue by LothaireCliquennois** [simoniz0r/Discord-AppImage#6]
I think that this AppImage is becoming quite obsolete as of now.

**Comment by simoniz0r** [comment]
I'm confused... 0.0.9 is the latest Discord Stable version.

**Comment by LothaireCliquennois** [comment]
Yeah, that's what I understand, the AppImage is downloading the updates itself...
However, since the 0.0.9 release that occured in early 2019, it has to download a lot of updates imo (it updates twice, which is very bad)
But yeah, in the meantime it still kind of works, just not ideal.

**Comment by simoniz0r** [comment]
All of those updates are server side and would happen with any packaging method used for Discord.  This is not the fault of the AppImage and cannot be prevented.  This is just how Discord works.
